### ISSUE TITLE
Refactor host list for better comprehension and clarity

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-vagrant#6]
Since the yaml configuration is read with Ruby, we should be able to change it and make it easier to understand. The current format is a list of lists. A dict of lists partitionned by type of nodes would be better and more idiomatic. And allow to define a generic topology for ansible with the groups `master`, `worker`, `edge` already defined. Another group, outside of this 3 groups might be useful.

The current host list is an array like:
```yaml
hosts:
  # |------ip-------|-hostname-|domain|cpus|memory|
  - ["192.168.56.10", edge-01, tdp, 2, 2048]
  - ["192.168.56.11", master-01, tdp, 3, 3072]
  - ["192.168.56.12", master-02, tdp, 3, 3072]
  - ["192.168.56.13", master-03, tdp, 3, 3072]
  - ["192.168.56.14", worker-01, tdp, 2, 2048]
  - ["192.168.56.15", worker-02, tdp, 2, 2048]
  - ["192.168.56.16", worker-03, tdp, 2, 2048]
```

This could become something like this
```yaml
hosts:
  edge:
    - name: ...
      ip: ...
      domain: ... # maybe consider domain as a cluster wide parameter ?
      cpus: ...
      memory: ...
  worker:
    - ...
 ...
```
